---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: article
    page colours:
      primary colour: "#91a3b0"
      secondary colour: "#fff"
      border colour: "#000"
      text colour: "#000"
      placeholder colour: grey
    page root:
      styles: 
    page header:
      is central: false
      override: 
      styles: 
    page navigation:
      styles: 
    page title:
      is displayed: true
      styles: 
    page content:
      content styles: 
      layout styles: 
    page footer:
      is displayed: true
      styles: 
- scope:
    path: ''
    type: pages
  values:
    permalink: "/:basename"
    page navigation:
      is navigable: false
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
- scope:
    path: secure
  values:
    permalink: "/:path/:basename"
    hidden: true
    sitemap: false
baseurl: 
url: https://jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
basabees: http://www.basharalidreesi.com
batabeet: "/"
theme: 
plugins:
- jekyll-feed
- jekyll-sitemap
- nokogiri
