---
title: Jad Toghuj
timezone: UTC
collections:
  social-media-and-content-creation:
    title: Clients
    output: true
  posts:
    title: Posts
    output: true
  styling-and-creative-direction:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    is_navigation_list_item: false
    navigation_list_item_order: 
    header_graphic_location: upper
    has_footer_container: false
- scope:
    path: 'styling-and-creative-direction'
  values:
    layout: project
- scope:
    path: assets/graphics/header_graphic_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tile_graphics
  values:
    showcase_tile: true
email: 
description: Jad Toghuj
author: Jad Toghuj
baseurl: 
url: 
twitter_username: 
github_username: 
theme: 
plugins:
- jekyll-feed
