---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    primary_colour: "#91a3b0"
    secondary_colour: "#fff"
    border_colour: "#000"
    text_colour: "#000"
    header_location: upper
    is_fullscreen: false
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_listed: false
- scope:
    path: ''
    type: styling-and-creative-direction
  values:
    layout: cascade
    is_fullscreen: true
- scope:
    path: ''
    type: social-media-and-content-creation
  values:
    layout: cascade
    is_fullscreen: true
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
baseurl: 
url: https://www.basharalidreesi.com/lab/
description: Jad Toghuj | Stylist & Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jadtoghuj"
theme: 
plugins:
- jekyll-feed
