---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_navigation_list_item: false
    navigation_list_item_order: 
    header_graphic_location: upper
    has_footer_container: false
- scope:
    path: assets/graphics/header_graphic_graphics
  values:
    image: true
email: 
description: Jad Toghuj
author: Jad Toghuj
baseurl: 
url: 
twitter_username: 
github_username: 
theme:
plugins:
- jekyll-feed
