---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    colours:
      primary colour: "#91a3b0"
      secondary colour: "#fff"
      border colour: "#000"
      text colour: "#000"
    fonts:
      families:
        navigation: M+ 1p
        footer: M+ 1p
        lists: M+ 1p
        tags: MD IO
        titles: Margo
        articles: M+ 1p
      sizes:
        navigation: temp
        footer: temp
        lists: temp
        tags: temp
        titles: temp
        articles: temp
      weights:
        navigation: 300
        footer: 300
        lists: 400
        tags: 400
        titles: 400
        articles: 400
    central header: false
    display title: true
    has central header: false
    has page title: true
- scope:
    path: ''
    type: pages
  values:
    permalink: "/:basename"
    layout: default
    is navigable: false
- scope:
    path: ''
    type: styling-and-creative-direction
  values:
    layout: cascade
- scope:
    path: ''
    type: social-media-and-content-creation
  values:
    layout: cascade
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
baseurl:
url: https://jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
basabees: http://www.basharalidreesi.com
batabeet: "/"
theme:
plugins:
- jekyll-feed
- jekyll-sitemap
