---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    primary_colour: "#91a3b0"
    secondary_colour: "#fff"
    border_colour: "#000"
    text_colour: "#000"
    colours:
    - primary: test
    - secondary: test
    - border: test
    - text: test
    fonts: test
    header_location: upper
- scope:
    path: ''
    type: pages
  values:
    permalink: "/:basename"
    layout: default
    is_listed: false
- scope:
    path: ''
    type: styling-and-creative-direction
  values:
    layout: cascade
- scope:
    path: ''
    type: social-media-and-content-creation
  values:
    layout: cascade
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
baseurl: 
url: https://www.jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
basabees: http://www.basharalidreesi.com
batabeet: "/"
theme: 
plugins:
- jekyll-feed
- jekyll-sitemap
