---
title: Jad Toghuj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: article
    page colours:
      primary colour: "#91a3b0"
      secondary colour: "#fff"
      border colour: "#000"
      text colour: "#000"
      placeholder colour: grey
    page root:
      styles:
    page header:
      is central: false
      override:
      styles:
    page navigation:
      styles:
    page content:
      is titled: false
      title styles:
      content styles:
    page layout:
      is titled: false
      subtext:
      styles:
    page footer:
      is displayed:
      title:
      subtext: 
      styles:
- scope:
    path: ''
    type: pages
  values:
    permalink: "/:basename"
    page navigation:
      is navigable: false
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
baseurl:
url: https://jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
basabees: http://www.basharalidreesi.com
batabeet: "/"
theme:
plugins:
- jekyll-feed
- jekyll-sitemap
