---
title: Jad Toghuj
timezone: UTC
collections:
  social-media-and-content-creation:
    title: Clients
    output: true
  posts:
    title: Posts
    output: true
  styling-and-creative-direction:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    primary_colour: "#91a3b0"
    secondary_colour: "#fff"
    border_colour: "#000"
    text_colour: "#000"
    header_location: upper
    is_fullscreen: false
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_listed: false
- scope:
    path: ''
    type: styling-and-creative-direction
  values:
    layout: cascade
    is_fullscreen: true
- scope:
    path: ''
    type: social-media-and-content-creation
  values:
    layout: cascade
    is_fullscreen: true
- scope:
    path: assets/graphics/header_graphics
  values:
    header_graphic: true
- scope:
    path: assets/graphics/showcase_tiles
  values:
    showcase_tile: true
email: 
description: Jad Toghuj
author: Jad Toghuj
baseurl: 
url: 
twitter_username: 
github_username: 
theme: 
plugins:
- jekyll-feed
