---
title: Jad Toghuj
timezone: UTC
collections:
  guide:
    title: Guide
    output: true
  posts:
    title: Posts
    output: true
  social-media-and-content-creation:
    title: Social Media & Content Creation
    output: true
    permalink: "/:collection/:path"
  styling-and-creative-direction:
    title: Styling & Creative Direction
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: article
    page colours:
      primary colour: "#91a3b0"
      secondary colour: "#fff"
      border colour: "#000"
      text colour: "#000"
      placeholder colour: grey
    page root:
      styles: 
    page header:
      is central: false
      image: 
      styles: 
    page navigation:
      styles: 
    page title:
      is displayed: true
      styles: 
    page content:
      content styles: 
      special styles: 
    page footer:
      is displayed: true
      styles: 
- scope:
    path: ''
    type: pages
  values:
    permalink: "/:basename"
    page navigation:
      is navigable: false
- scope:
    path: assets/fonts
  values:
    font: true
baseurl: 
url: https://jadtoghuj.com
description: Jad Toghuj | Editorial Stylist | Creative Director | Amman, Jordan
author: Jad Toghuj
email: jadtoghuj@gmail.com
instagram: "@jad.toghuj"
footer text: By <a class="--anchor_styling" href="https://basharalidreesi.com">Basabees</a>
  for <a class="--anchor_styling" href="/">Batabeet</a>
header images:
- "/uploads/header-01.svg"
- "/uploads/header-02.svg"
- "/uploads/header-03.svg"
- "/uploads/header-04.svg"
- "/uploads/header-05.svg"
- "/uploads/header-06.svg"
- "/uploads/header-07.svg"
- "/uploads/header-08.svg"
- "/uploads/header-09.svg"
- "/uploads/header-10.svg"
- "/uploads/header-11.svg"
plugins:
- jekyll-feed
- jekyll-sitemap
